import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, collection, doc, onSnapshot, setDoc, deleteDoc, getDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyA_CbiovvY9yvdsQ6wzzwoG2QaqBT0r7Bg",authDomain:"allsetrepportal.firebaseapp.com",projectId:"allsetrepportal",storageBucket:"allsetrepportal.firebasestorage.app",messagingSenderId:"590070052736",appId:"1:590070052736:web:193a9edb6fd378fbd27365",measurementId:"G-SY45913J3Z",databaseURL:"https://allsetrepportal-default-rtdb.firebaseio.com"};
const app=getApps()[0]||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const money=n=>"$"+Number(n||0).toLocaleString();
const ADMIN_CODE="2122";
let uid="",role="rep",name="Team",adminUnlocked=sessionStorage.getItem("allset_admin_unlocked")==="1";
let reps={},leads={},jobs={},customers={},dots={},neighborhoods={},chat={},subscribed=false,activeChannel="General";
let map=null,dotLayer=null,territoryLayer=null,drawHandler=null,mapMode="";

window.addEventListener("DOMContentLoaded",bootOps);
function bootOps(){injectCss();ensureChat();wire();refreshUser();applyNav();signInAnonymously(auth).catch(()=>{});onAuthStateChanged(auth,u=>{uid=u?.uid||uid;subscribe();});setInterval(tick,1200);}
function tick(){refreshUser();applyNav();syncChatButton();renderAll();initMapIfNeeded();}
function subscribe(){if(subscribed)return;subscribed=true;onSnapshot(collection(db,"reps"),s=>{reps=snapObj(s);renderAll()});onSnapshot(collection(db,"leads"),s=>{leads=snapObj(s);renderAll()});onSnapshot(collection(db,"jobs"),s=>{jobs=snapObj(s);renderAll()});onSnapshot(collection(db,"customers"),s=>{customers=snapObj(s);renderAll()});onSnapshot(collection(db,"dots"),s=>{dots=snapObj(s);renderMapDots()});onSnapshot(collection(db,"neighborhoods"),s=>{neighborhoods=snapObj(s);renderTerritories();renderTerritoryList()});onSnapshot(collection(db,"chatMessages"),s=>{chat=snapObj(s);renderChat()});}
function snapObj(s){const o={};s.forEach(d=>o[d.id]={...d.data(),id:d.data().id||d.id});return o}
function refreshUser(){role=localStorage.getItem("allset_rep_role")||$("roleSelect")?.value||role||"rep";name=localStorage.getItem("allset_rep_name")||$("nicknameInput")?.value||name||"Team"}

function wire(){
  document.addEventListener("click",gateLockedNav,true);
  document.addEventListener("click",e=>{
    const btn=e.target.closest("[data-map-mode]");if(btn){setMapMode(btn.dataset.mapMode);return;}
    const dotBtn=e.target.closest("[data-dot-action]");if(dotBtn){handleDotAction(dotBtn);return;}
    const areaBtn=e.target.closest("[data-area-action]");if(areaBtn){handleAreaAction(areaBtn);return;}
    const ch=e.target.closest(".chatChannel");if(ch){activeChannel=ch.dataset.channel;document.querySelectorAll(".chatChannel").forEach(b=>b.classList.toggle("active",b.dataset.channel===activeChannel));renderChat();return;}
    if(e.target.closest("#dashboardChatBtn")){openChat();return;}
    if(e.target.closest("#closeChatBtn")||e.target.closest("#chatScrim")){closeChat();return;}
    if(e.target.closest("#chatSendBtn")){sendChat();return;}
    const del=e.target.closest("[data-delete-chat]");if(del){deleteChat(del.dataset.deleteChat);return;}
    const team=e.target.closest("[data-delete-team]");if(team){deleteTeam(team.dataset.deleteTeam,team.dataset.name);return;}
  });
  document.addEventListener("keydown",e=>{if(e.target?.id==="chatInput"&&e.key==="Enter")sendChat();if(e.key==="Escape")closeChat();});
  $("enterBtn")?.addEventListener("click",()=>setTimeout(tick,250));
}
function gateLockedNav(e){const b=e.target.closest(".navBtn");if(!b)return;const page=b.dataset.page;if(!["admin","equipment"].includes(page))return;if(isAdmin())return;const code=prompt("Enter admin password:");if(code!==ADMIN_CODE){e.preventDefault();e.stopImmediatePropagation();toast("Wrong password");return;}adminUnlocked=true;sessionStorage.setItem("allset_admin_unlocked","1");applyNav();}
function isAdmin(){return role==="admin"||adminUnlocked}
function applyNav(){const allowed={rep:["dashboard","map","leads","jobs","leaderboard","payments","admin","equipment"],cleaner:["dashboard","jobs","board","schedule","payments","admin","equipment"],admin:["dashboard","map","leads","jobs","leaderboard","board","schedule","customers","team","payments","admin","equipment"]}[role]||[];document.querySelectorAll(".navBtn").forEach(b=>{const p=b.dataset.page;b.classList.toggle("hidden",!allowed.includes(p));b.classList.toggle("navBtn--locked",["admin","equipment"].includes(p)&&!isAdmin());});document.querySelectorAll(".adminOnly").forEach(el=>el.classList.toggle("hidden",!isAdmin()));badgeJobs();}
function renderAll(){renderLeaderboard();renderBoard();if(role==="cleaner")renderCleanerJobs();badgeJobs();syncChatButton();}

function renderLeaderboard(){const el=$("leaderboardTable");if(!el)return;const rows=new Map();Object.entries(reps).filter(([,r])=>(r.role||"rep")==="rep").forEach(([id,r])=>rows.set(id,{id,name:r.name||"Rep",revenue:0,sold:0,converted:0,total:0}));Object.values(leads).forEach(l=>{const id=l.repId||l.repName||"unknown";if(!rows.has(id))rows.set(id,{id,name:l.repName||reps[l.repId]?.name||"Rep",revenue:0,sold:0,converted:0,total:0});const r=rows.get(id);r.total++;if(["sold","converted"].includes(String(l.status||"").toLowerCase())){r.converted++;r.revenue+=Number(l.quote||0)}});Object.values(jobs).forEach(j=>{const id=j.repId||j.repName||"unknown";if(!rows.has(id))rows.set(id,{id,name:j.repName||reps[j.repId]?.name||"Rep",revenue:0,sold:0,converted:0,total:0});const r=rows.get(id);r.sold++;r.revenue+=Number(j.price||j.amount||0)});const manage=isAdmin();const body=[...rows.values()].sort((a,b)=>b.revenue-a.revenue).map(r=>`<tr><td><strong>${esc(r.name)}</strong></td><td>${money(r.revenue)}</td><td>${r.sold}</td><td>${r.converted}</td><td>${r.total?Math.round(r.converted/r.total*100):0}%</td>${manage?`<td>${reps[r.id]?`<button class="dangerBtn smallBtn" data-delete-team="${esc(r.id)}" data-name="${esc(r.name)}">Delete</button>`:""}</td>`:""}</tr>`);table(el,manage?["Rep","Revenue","Sold Jobs","Leads Converted","Close Rate",""]:["Rep","Revenue","Sold Jobs","Leads Converted","Close Rate"],body,"No leaderboard data yet.");}
function renderBoard(){const el=$("boardTable");if(!el)return;const rows=new Map();Object.entries(reps).filter(([,r])=>r.role==="cleaner").forEach(([id,r])=>rows.set(id,{id,name:r.name||"Cleaner",claimed:0,completed:0,earned:0}));Object.values(jobs).forEach(j=>{const id=j.cleanerId||j.cleanerName||j.cleaner||"unassigned";if(!rows.has(id))rows.set(id,{id,name:j.cleanerName||j.cleaner||"Unassigned",claimed:0,completed:0,earned:0});const r=rows.get(id),s=jobStatus(j.status);if(j.claimedAt||["claimed","in_progress","completed"].includes(s)||j.cleanerName||j.cleaner)r.claimed++;if(s==="completed"||j.completedAt||j.cleanedAt){r.completed++;r.earned+=cleanerPay(j)}});const manage=isAdmin();const body=[...rows.values()].sort((a,b)=>b.earned-a.earned||b.completed-a.completed).map(r=>`<tr><td><strong>${esc(r.name)}</strong></td><td>${r.claimed}</td><td>${r.completed}</td><td>${money(r.earned)}</td>${manage?`<td>${reps[r.id]?`<button class="dangerBtn smallBtn" data-delete-team="${esc(r.id)}" data-name="${esc(r.name)}">Delete</button>`:""}</td>`:""}</tr>`);table(el,manage?["Cleaner","Jobs Claimed","Jobs Completed","Amount Earned",""]:["Cleaner","Jobs Claimed","Jobs Completed","Amount Earned"],body,"No cleaner board data yet.");}
function renderCleanerJobs(){const el=$("jobsTable");if(!el)return;const mine=j=>j.cleanerId===uid||j.cleanerName===name||j.cleaner===name;const rows=Object.values(jobs).filter(j=>jobStatus(j.status)==="open"||mine(j)).map(j=>`<tr><td><strong>${esc(j.customer||j.title||"Job")}</strong><br><span class="muted">${esc(j.address||"")}</span></td><td>${esc(j.phone||"-")}</td><td>${esc(readableDate(j.scheduledAt)||"-")}</td><td><span class="status ${jobStatus(j.status)}">${esc(labelStatus(j.status))}</span></td><td>${esc(j.repName||"-")}</td><td>${esc(j.cleanerName||j.cleaner||"-")}</td><td>${cleanerPay(j)?money(cleanerPay(j)):'<span class="muted">Not set</span>'}</td><td><div class="tableActions">${jobButtons(j,mine(j))}</div></td></tr>`);el.innerHTML=rows.length?`<table class="dataTable"><thead><tr><th>Job</th><th>Phone</th><th>Scheduled</th><th>Status</th><th>Rep</th><th>Cleaner</th><th>Cleaner Pay</th><th></th></tr></thead><tbody>${rows.join("")}</tbody></table>`:`<div class="card">No open jobs yet.</div>`;}
function jobButtons(j,mine){const s=jobStatus(j.status);if(s==="open")return`<button class="actionBtn smallBtn" onclick="window.opsClaimJob('${esc(j.id)}')">Claim Job</button>`;if(s==="claimed"&&mine)return`<button class="actionBtn smallBtn" onclick="window.opsStartJob('${esc(j.id)}')">Start Job</button>`;if(s==="in_progress"&&mine)return`<button class="actionBtn smallBtn" onclick="window.opsCompleteJob('${esc(j.id)}')">Complete Job</button>`;return"";}
window.opsClaimJob=async id=>{const j=jobs[id];if(!j||jobStatus(j.status)!=="open")return toast("Already claimed");const t=Date.now();await setDoc(doc(db,"jobs",id),{status:"claimed",cleanerId:uid,cleanerName:name,cleaner:name,claimedAt:t,updatedAt:t,updatedBy:name},{merge:true});log(`Job claimed: ${j.customer||j.title||id} by ${name}`)};
window.opsStartJob=async id=>{const j=jobs[id];if(!j)return;const t=Date.now();await setDoc(doc(db,"jobs",id),{status:"in_progress",startedAt:t,updatedAt:t,updatedBy:name},{merge:true});log(`Job started: ${j.customer||j.title||id}`)};
window.opsCompleteJob=async id=>{const j=jobs[id];if(!j)return;const t=Date.now();await setDoc(doc(db,"jobs",id),{status:"completed",completedAt:t,cleanedAt:t,lastCleanedAt:t,updatedAt:t,updatedBy:name},{merge:true});log(`Job completed: ${j.customer||j.title||id}`)};
async function deleteTeam(id,label){if(!isAdmin())return toast("Admin password required");if(!id||!reps[id])return toast("This row is job history, not a team record");if(confirm(`Delete ${label||"team member"}?`)){await deleteDoc(doc(db,"reps",id));toast("Deleted");}}

function initMapIfNeeded(){const el=$("map");if(map||!el||!window.L)return;if(window.allsetMap){map=window.allsetMap}else{map=L.map(el).setView([41.6611,-91.5302],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:"&copy; OpenStreetMap"}).addTo(map);window.allsetMap=map;}dotLayer=L.layerGroup().addTo(map);territoryLayer=L.layerGroup().addTo(map);map.on("click",mapClick);map.on(L.Draw.Event.CREATED,drawCreated);wireMapButtons();setTimeout(()=>map.invalidateSize(),100);renderMapDots();renderTerritories();}
function wireMapButtons(){[["addDotBtn","add"],["drawBtn","draw"],["assignAreaBtn","assign"],["gpsBtn","gps"]].forEach(([id,m])=>$(id)?.setAttribute("data-map-mode",m));}
async function mapClick(e){if(mapMode!=="add")return;const label=prompt("House label or address:")||"House";const id=`dot-${Date.now()}`;await setDoc(doc(db,"dots",id),{id,label,address:label,lat:e.latlng.lat,lng:e.latlng.lng,status:"none",notes:"",createdAt:Date.now(),createdBy:name},{merge:true});setMapMode("");}
function setMapMode(next){if(next==="gps"){useGps();return;}if(drawHandler){drawHandler.disable();drawHandler=null;}mapMode=mapMode===next?"":next;document.querySelectorAll("[data-map-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mapMode===mapMode));if(mapMode==="draw"&&map&&L.Draw){drawHandler=new L.Draw.Polygon(map,{shapeOptions:{color:"#38bdf8",fillOpacity:.14}});drawHandler.enable();}toast(mapMode?`${mapMode} mode on`:"Map mode off");}
async function drawCreated(e){if(mapMode!=="draw")return;const id=`nb-${Date.now()}`,areaName=prompt("Neighborhood name:")||"Neighborhood",color=prompt("Color: green, red, blue, purple, orange, gray","blue")||"blue",repName=prompt("Assigned rep name (optional):","")||"";const hex={green:"#22c55e",red:"#ef4444",blue:"#38bdf8",purple:"#a855f7",orange:"#f59e0b",gray:"#94a3b8"}[color]||"#38bdf8";await setDoc(doc(db,"neighborhoods",id),{id,name:areaName,color:hex,colorName:color,assignedRepId:"",assignedRepName:repName,notes:"",geojson:e.layer.toGeoJSON(),createdAt:Date.now(),updatedAt:Date.now(),createdBy:name,updatedBy:name},{merge:true});setMapMode("");}
function renderMapDots(){if(!dotLayer)return;dotLayer.clearLayers();Object.values(dots).forEach(d=>{if(!Number.isFinite(Number(d.lat))||!Number.isFinite(Number(d.lng)))return;const m=L.circleMarker([d.lat,d.lng],{radius:10,weight:4,color:dotColor(d.status),fillColor:dotColor(d.status),fillOpacity:.88}).addTo(dotLayer);m.on("click",ev=>{L.DomEvent.stopPropagation(ev);if(mapMode==="delete")return deleteDot(d.id);m.bindPopup(dotPopup(d),{maxWidth:285,className:"compactDotPopup"}).openPopup();});});updateDotCounts();}
function dotPopup(d){return`<div class="mapMiniPopup"><strong>${esc(d.label||d.address||"House")}</strong><textarea data-dot-notes="${esc(d.id)}" placeholder="Notes">${esc(d.notes||"")}</textarea><div class="statusGrid"><button data-dot-action="status" data-id="${esc(d.id)}" data-status="yes">Yes</button><button data-dot-action="status" data-id="${esc(d.id)}" data-status="no">No</button><button data-dot-action="status" data-id="${esc(d.id)}" data-status="not_home">Not Home</button><button data-dot-action="status" data-id="${esc(d.id)}" data-status="callback">Callback</button><button data-dot-action="status" data-id="${esc(d.id)}" data-status="none">Unmarked</button></div><div class="tableActions"><button data-dot-action="lead" data-id="${esc(d.id)}">Move to Lead</button><button data-dot-action="job" data-id="${esc(d.id)}">Move to Job</button><button data-dot-action="delete" data-id="${esc(d.id)}">Delete</button></div></div>`;}
async function handleDotAction(b){const id=b.dataset.id,d=dots[id];if(!d)return;const action=b.dataset.dotAction;if(action==="delete")return deleteDot(id);if(action==="lead")return moveDot(id,"lead");if(action==="job")return moveDot(id,"job");const notes=document.querySelector(`[data-dot-notes="${CSS.escape(id)}"]`)?.value||d.notes||"";await setDoc(doc(db,"dots",id),{status:b.dataset.status||"none",notes,updatedAt:Date.now(),updatedBy:name,lastKnockedAt:Date.now()},{merge:true});map?.closePopup();}
async function moveDot(id,type){const d=dots[id];if(!d)return;const t=Date.now();if(type==="lead"){const lid=`lead-${t}`;await setDoc(doc(db,"leads",lid),{id:lid,customer:d.label||d.address||"Map Lead",address:d.address||d.label||"",phone:"",status:"new",quote:0,notes:d.notes||"",repName:name,repId:uid,createdAt:t,createdBy:name,sourceDotId:id},{merge:true});}else{const jid=`job-${t}`;await setDoc(doc(db,"jobs",jid),{id:jid,customer:d.label||d.address||"Map Job",address:d.address||d.label||"",phone:"",status:"open",price:0,payCleanerAmount:0,notes:d.notes||"",repName:name,repId:uid,createdAt:t,createdBy:name,sourceDotId:id},{merge:true});}await deleteDoc(doc(db,"dots",id));map?.closePopup();toast(type==="lead"?"Moved to Leads":"Moved to Jobs");}
async function deleteDot(id){if(confirm("Delete this house dot?"))await deleteDoc(doc(db,"dots",id));}
function renderTerritories(){if(!territoryLayer)return;territoryLayer.clearLayers();Object.values(neighborhoods).forEach(n=>{if(!n.geojson)return;const g=L.geoJSON(n.geojson,{style:{color:n.color||"#38bdf8",weight:4,fillColor:n.color||"#38bdf8",fillOpacity:.13}});g.eachLayer(layer=>{layer.on("click",e=>{L.DomEvent.stopPropagation(e);if(mapMode==="delete")return deleteTerritory(n.id);if(mapMode==="assign")return assignTerritory(n.id);layer.bindPopup(areaPopup(n),{maxWidth:260}).openPopup(e.latlng);});territoryLayer.addLayer(layer);});});}
function areaPopup(n){return`<strong>${esc(n.name||"Area")}</strong><br><span class="muted">${n.assignedRepName?`Assigned: ${esc(n.assignedRepName)}`:"Unassigned"}</span><div class="tableActions" style="margin-top:8px"><button data-area-action="assign" data-id="${esc(n.id)}">Assign</button><button data-area-action="delete" data-id="${esc(n.id)}">Delete</button></div>`;}
function renderTerritoryList(){const box=$("territoryList");if(!box)return;const rows=Object.values(neighborhoods).map(n=>`<div class="territoryItem"><span><span class="territorySwatch" style="background:${esc(n.color||"#38bdf8")}"></span><strong>${esc(n.name||"Area")}</strong><br><span class="muted">${n.assignedRepName?`Assigned: ${esc(n.assignedRepName)}`:"Unassigned"}</span></span><span class="tableActions"><button class="ghostBtn smallBtn" data-area-action="assign" data-id="${esc(n.id)}">Assign</button><button class="dangerBtn smallBtn" data-area-action="delete" data-id="${esc(n.id)}">Delete</button></span></div>`);box.innerHTML=rows.length?rows.join(""):'<div class="muted">No areas drawn yet.</div>';}
async function handleAreaAction(b){if(b.dataset.areaAction==="delete")return deleteTerritory(b.dataset.id);if(b.dataset.areaAction==="assign")return assignTerritory(b.dataset.id);}
async function assignTerritory(id){const n=neighborhoods[id];if(!n)return;const rep=prompt("Assign to rep name. Leave blank to unassign:",n.assignedRepName||"");if(rep===null)return;await setDoc(doc(db,"neighborhoods",id),{assignedRepName:rep.trim(),assignedRepId:"",updatedAt:Date.now(),updatedBy:name},{merge:true});toast(rep.trim()?"Area assigned":"Area unassigned");}
async function deleteTerritory(id){const n=neighborhoods[id];if(confirm(`Delete ${n?.name||"this territory"}?`))await deleteDoc(doc(db,"neighborhoods",id));}
function useGps(){if(!navigator.geolocation)return toast("GPS not available");navigator.geolocation.getCurrentPosition(pos=>map?.setView([pos.coords.latitude,pos.coords.longitude],16),err=>toast(err.message));}
function dotColor(s){s=String(s||"none").toLowerCase().replace(/[_ -]/g,"");if(["yes","closed","sold"].includes(s))return"#22c55e";if(s==="no")return"#ef4444";if(["nothome","not_home","noanswer"].includes(s))return"#38bdf8";if(["callback","followup"].includes(s))return"#a855f7";return"#9ca3af";}
function updateDotCounts(){const c={yes:0,no:0,nothome:0,callback:0};Object.values(dots).forEach(d=>{const color=dotColor(d.status);if(color==="#22c55e")c.yes++;else if(color==="#ef4444")c.no++;else if(color==="#38bdf8")c.nothome++;else if(color==="#a855f7")c.callback++;});setText("countYes",c.yes);setText("countNo",c.no);setText("countNotHome",c.nothome);setText("countCallback",c.callback);}

function ensureChat(){if(!$("dashboardChatBtn"))document.body.insertAdjacentHTML("beforeend",`<button id="dashboardChatBtn" class="dashboardChatBtn" type="button">Chat</button>`);if(!$("chatDrawer"))document.body.insertAdjacentHTML("beforeend",`<div id="chatScrim" class="chatScrim"></div><aside id="chatDrawer" class="chatDrawer"><div class="chatTop"><strong>Team Chat</strong><button id="closeChatBtn" class="ghostBtn smallBtn" type="button">Close</button></div><div class="chatChannels"><button class="chatChannel active" data-channel="General">General</button><button class="chatChannel" data-channel="Sales">Sales</button><button class="chatChannel" data-channel="Cleaning">Cleaning</button><button class="chatChannel" data-channel="Announcements">Announcements</button></div><div id="chatMessages" class="chatMessages"></div><div class="chatComposer"><input id="chatInput" placeholder="Message the team" /><button id="chatSendBtn" class="actionBtn" type="button">Send</button></div></aside>`);}
function syncChatButton(){const on=$("page-dashboard")?.classList.contains("active");document.body.classList.toggle("dashboard-chat-visible",!!on);if(!on)closeChat();}
function openChat(){$("chatDrawer")?.classList.add("open");$("chatScrim")?.classList.add("open");renderChat();}
function closeChat(){$("chatDrawer")?.classList.remove("open");$("chatScrim")?.classList.remove("open");}
async function sendChat(){const input=$("chatInput"),text=input?.value.trim();if(!text)return;if(activeChannel==="Announcements"&&!isAdmin())return toast("Only admin can post announcements");const id=`chat-${Date.now()}`;await setDoc(doc(db,"chatMessages",id),{id,channel:activeChannel,text,senderId:uid,senderName:name,senderRole:role,createdAt:Date.now()},{merge:true});input.value="";}
function renderChat(){const box=$("chatMessages");if(!box)return;const msgs=Object.values(chat).filter(m=>(m.channel||"General")===activeChannel).sort((a,b)=>dateVal(a.createdAt)-dateVal(b.createdAt)).slice(-80);box.innerHTML=msgs.length?msgs.map(m=>`<div class="chatMsg"><div><strong>${esc(m.senderName||"Team")}</strong> <span>${esc(chatStamp(m.createdAt))}</span>${isAdmin()||m.senderId===uid?`<button data-delete-chat="${esc(m.id)}">x</button>`:""}</div><p>${esc(m.text||"")}</p></div>`).join(""):`<div class="muted">No messages yet.</div>`;box.scrollTop=box.scrollHeight;}
async function deleteChat(id){if(id&&confirm("Delete this message?"))await deleteDoc(doc(db,"chatMessages",id));}

function badgeJobs(){const count=Object.values(jobs).filter(j=>jobStatus(j.status)==="open").length;document.querySelectorAll('.navBtn[data-page="jobs"]').forEach(b=>{const show=role==="cleaner"&&count>0;b.classList.toggle("hasOpenJobs",show);b.dataset.openCount=show?String(count):"";});}
function table(el,headers,rows,empty){el.innerHTML=rows.length?`<table class="dataTable"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table>`:`<div class="card">${empty}</div>`;}
function cleanerPay(j){return Number(j.payCleanerAmount??j.cleanerPay??j.cleanerAmount??j.payCleaner??0)}
function jobStatus(s){s=String(s||"open").toLowerCase().replace(/\s+/g,"_").replace("-","_");return s==="scheduled"?"open":s}
function labelStatus(s){return jobStatus(s).replaceAll("_"," ").replace(/^./,c=>c.toUpperCase())}
function dateVal(v){if(!v)return 0;if(typeof v==="number")return v;if(v.seconds)return v.seconds*1000;const t=new Date(v).getTime();return Number.isFinite(t)?t:0}
function readableDate(v){const t=dateVal(v);return t?new Date(t).toLocaleString([],{month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit"}):""}
function chatStamp(v){const t=dateVal(v);if(!t)return"";const d=new Date(t),n=new Date(),day=new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime(),today=new Date(n.getFullYear(),n.getMonth(),n.getDate()).getTime(),time=d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}),diff=Math.round((today-day)/86400000);if(diff<=0)return time;if(diff===1)return`Yesterday ${time}`;if(diff<7)return`${d.toLocaleDateString([],{weekday:"long"})} ${time}`;return`${d.toLocaleDateString([],{month:"2-digit",day:"2-digit",year:"numeric"})} ${time}`}
function setText(id,v){const el=$(id);if(el)el.textContent=String(v)}
async function log(text){try{const ref=doc(db,"shared","activityLog"),snap=await getDoc(ref),entries=snap.exists()?(snap.data().entries||[]):[];await setDoc(ref,{entries:[{t:Date.now(),text},...entries].slice(0,150)},{merge:true})}catch(e){}}
function toast(msg){const el=$("toast");if(!el)return;el.textContent=msg;el.classList.remove("hidden");clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add("hidden"),1800)}
function injectCss(){if($("opsCss"))return;const s=document.createElement("style");s.id="opsCss";s.textContent=`.navBtn{position:relative}.navBtn--locked{opacity:.78;border-style:dashed}.navBtn.hasOpenJobs::after{content:attr(data-open-count);position:absolute;right:10px;top:50%;transform:translateY(-50%);min-width:20px;height:20px;border-radius:999px;background:#ef4444;color:white;font-size:11px;font-weight:900;display:grid;place-items:center}.dashboardChatBtn{position:fixed;right:16px;bottom:88px;z-index:1000;padding:13px 16px;border-radius:16px;background:linear-gradient(90deg,var(--accent1),var(--accent2));color:#06101a;box-shadow:0 16px 38px rgba(0,0,0,.35)}body:not(.dashboard-chat-visible) .dashboardChatBtn{display:none}.chatScrim{position:fixed;inset:0;background:rgba(0,0,0,.2);opacity:0;pointer-events:none;z-index:1190}.chatScrim.open{opacity:1;pointer-events:auto}.chatDrawer{position:fixed;top:78px;right:12px;bottom:16px;width:min(390px,calc(100vw - 22px));z-index:1200;display:grid;grid-template-rows:auto auto 1fr auto;background:rgba(8,13,23,.97);border:1px solid rgba(255,255,255,.15);border-radius:18px;box-shadow:0 24px 80px rgba(0,0,0,.55);transform:translateX(calc(100% + 30px));transition:.2s;overflow:hidden}.chatDrawer.open{transform:translateX(0)}.chatTop{display:flex;justify-content:space-between;align-items:center;padding:14px;border-bottom:1px solid rgba(255,255,255,.1)}.chatChannels{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;padding:12px}.chatChannel{border-radius:12px;background:rgba(255,255,255,.07);color:var(--text);border:1px solid rgba(255,255,255,.12);min-height:40px}.chatChannel.active{border-color:rgba(56,189,248,.55);background:rgba(56,189,248,.18)}.chatMessages{overflow:auto;padding:12px;display:flex;flex-direction:column;gap:9px}.chatMsg{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.06);border-radius:12px;padding:10px}.chatMsg span{color:var(--muted);font-size:12px}.chatMsg button{float:right;border-radius:999px}.chatMsg p{margin:5px 0 0}.chatComposer{display:grid;grid-template-columns:1fr auto;gap:8px;padding:12px;border-top:1px solid rgba(255,255,255,.1)}.territoryItem{display:flex;justify-content:space-between;gap:10px;padding:10px;border-radius:12px;background:rgba(255,255,255,.05);margin-bottom:8px}.territorySwatch{display:inline-block;width:10px;height:10px;border-radius:999px;margin-right:7px}.compactDotPopup .leaflet-popup-content{margin:10px}.mapMiniPopup{width:245px;color:#07111d}.mapMiniPopup textarea{width:100%;min-height:58px;margin:8px 0}.statusGrid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.statusGrid button,.mapMiniPopup button{min-height:34px;border-radius:10px}@media(max-width:720px){#mobileNavBtn{padding:15px 19px;font-size:16px}.chatDrawer{top:70px;right:8px;bottom:8px;width:calc(100vw - 16px)}}`;document.head.appendChild(s);}
