import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, doc, onSnapshot, setDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyA_CbiovvY9yvdsQ6wzzwoG2QaqBT0r7Bg",authDomain:"allsetrepportal.firebaseapp.com",projectId:"allsetrepportal",storageBucket:"allsetrepportal.firebasestorage.app",messagingSenderId:"590070052736",appId:"1:590070052736:web:193a9edb6fd378fbd27365",measurementId:"G-SY45913J3Z",databaseURL:"https://allsetrepportal-default-rtdb.firebaseio.com"};
const app=getApps()[0]||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
const methods=[{key:"cashApp",label:"Cash App",link:"cashAppLink",tag:"cashAppTag",input:"setCashApp"},{key:"venmo",label:"Venmo",link:"venmoLink",tag:"venmoTag",input:"setVenmo"},{key:"paypal",label:"PayPal",link:"paypalLink",tag:"paypalTag",input:"setPaypal"}];
let settings={},uid="";

window.addEventListener("DOMContentLoaded",bootPaymentImages);
function bootPaymentImages(){injectCss();ensureModal();signInAnonymously(auth).catch(()=>{});onAuthStateChanged(auth,u=>{uid=u?.uid||uid;watchSettings();});document.addEventListener("click",handleClick);document.addEventListener("change",handleChange);setInterval(()=>{upgradeAdmin();applyButtons();},1500);}
function watchSettings(){if(watchSettings.done)return;watchSettings.done=true;onSnapshot(doc(db,"shared","settings"),snap=>{settings=snap.exists()?snap.data():{};upgradeAdmin();applyButtons();});}
function handleClick(e){const pay=e.target.closest("[data-pay-image]");if(pay){e.preventDefault();openPayModal(pay.dataset.payImage);return;}if(e.target.closest("#payImageClose")||e.target.closest("#payImageBackdrop")){closePayModal();return;}if(e.target?.id==="saveSettingsBtn")saveSettings();const clear=e.target.closest("[data-clear-pay-image]");if(clear)clearImage(clear.dataset.clearPayImage);}
async function handleChange(e){const input=e.target.closest("input[data-pay-upload]");if(!input||!input.files?.[0])return;try{input.dataset.imageData=await compressImage(input.files[0]);preview(input.dataset.payUpload,input.dataset.imageData,"Ready to save");toast("Image ready. Click Save Settings.");}catch(err){toast(err.message||"Could not load image");}}

function upgradeAdmin(){const grid=$("setCashApp")?.closest(".formGrid");if(!grid)return;["setCashAppQr","setVenmoQr","setPaypalQr","setZelleQr"].forEach(id=>$(id)?.closest("label")?.remove());methods.forEach(m=>{if(document.querySelector(`[data-pay-wrap="${m.key}"]`))return;const label=document.createElement("label");label.dataset.payWrap=m.key;label.innerHTML=`${m.label} Image<input type="file" accept="image/*" data-pay-upload="${m.key}" /><span class="payImageHint">Upload the scan picture customers should use.</span><span class="payPreview" data-pay-preview="${m.key}"></span><button class="dangerBtn smallBtn" type="button" data-clear-pay-image="${m.key}">Remove Image</button>`;($(m.input)?.closest("label")||grid.lastElementChild)?.after(label);});methods.forEach(m=>preview(m.key,imageFor(m.key),imageFor(m.key)?"Saved image":"No image saved"));}
function applyButtons(){methods.forEach(m=>{const a=$(m.link);if(!a)return;a.href="#";a.removeAttribute("target");a.dataset.payImage=m.key;const tag=$(m.tag);if(tag)tag.textContent=settings[m.key]||defaultTag(m.key);let state=a.querySelector(".payImageState");if(!state){state=document.createElement("small");state.className="payImageState";a.appendChild(state);}state.textContent=imageFor(m.key)?"Tap to show scan image":"No image saved";});setText("zelleTag",settings.zelle||"Zelle info not set");}
async function saveSettings(){const patch={cashApp:$("setCashApp")?.value||settings.cashApp||"",venmo:$("setVenmo")?.value||settings.venmo||"",paypal:$("setPaypal")?.value||settings.paypal||"",zelle:$("setZelle")?.value||settings.zelle||"",updatedAt:Date.now(),updatedBy:localStorage.getItem("allset_rep_name")||"Team"};methods.forEach(m=>{const upload=document.querySelector(`input[data-pay-upload="${m.key}"]`);patch[`${m.key}Image`]=upload?.dataset.imageData||settings[`${m.key}Image`]||"";patch[`${m.key}Qr`]="";});await setDoc(doc(db,"shared","settings"),patch,{merge:true});toast("Payment settings saved");}
async function clearImage(key){if(!confirm("Remove this payment image?"))return;const patch={updatedAt:Date.now()};patch[`${key}Image`]="";patch[`${key}Qr`]="";await setDoc(doc(db,"shared","settings"),patch,{merge:true});}

function openPayModal(key){const img=imageFor(key),m=methods.find(x=>x.key===key);$("payImageTitle").textContent=m?.label||"Payment";$("payImageBody").innerHTML=img?`<img class="payScan" src="${img}" alt="${m?.label||"Payment"} scan image" /><div class="payScanTag">${escapeHtml(settings[key]||defaultTag(key))}</div>`:`<div class="payMissing">No ${m?.label||"payment"} image saved yet.</div>`;$("payImageModal")?.classList.remove("hidden");}
function closePayModal(){$("payImageModal")?.classList.add("hidden")}
function ensureModal(){if($("payImageModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="payImageModal" class="payImageModal hidden"><div id="payImageBackdrop" class="payImageBackdrop"></div><div class="payImageCard"><div class="payImageTop"><strong id="payImageTitle">Payment</strong><button id="payImageClose" class="ghostBtn smallBtn" type="button">Close</button></div><div id="payImageBody" class="payImageBody"></div></div></div>`);}
function preview(key,img,text){const el=document.querySelector(`[data-pay-preview="${key}"]`);if(el)el.innerHTML=img?`<img src="${img}" alt="" /><span>${text}</span>`:`<span>${text}</span>`;}
function imageFor(key){return settings[`${key}Image`]||settings[`${key}Qr`]||"";}
function defaultTag(key){return{cashApp:"$NotS1ick",venmo:"@notslik",paypal:"PayPal"}[key]||"";}
function setText(id,v){const el=$(id);if(el)el.textContent=v;}
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function toast(msg){const el=$("toast");if(!el)return;el.textContent=msg;el.classList.remove("hidden");clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add("hidden"),2000);}
function readFile(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(new Error("Could not read image"));r.readAsDataURL(file);});}
function loadImage(src){return new Promise((res,rej)=>{const img=new Image();img.onload=()=>res(img);img.onerror=()=>rej(new Error("Could not load image"));img.src=src;});}
async function compressImage(file){if(!file.type.startsWith("image/"))throw new Error("Choose an image file");const img=await loadImage(await readFile(file));const max=900,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let q=.78,data=canvas.toDataURL("image/jpeg",q);while(data.length>300000&&q>.42){q-=.08;data=canvas.toDataURL("image/jpeg",q);}if(data.length>450000)throw new Error("Image is too large. Try a tighter screenshot.");return data;}
function injectCss(){if($("paymentImageCss"))return;const s=document.createElement("style");s.id="paymentImageCss";s.textContent=`.payImageState{display:block;margin-top:8px;color:var(--muted);font-size:11px}.payImageHint{display:block;color:var(--muted);font-size:11px;margin-top:6px}.payPreview{display:grid;gap:6px;place-items:center;min-height:82px;margin-top:8px;border:1px dashed rgba(255,255,255,.18);border-radius:12px;background:rgba(0,0,0,.14);overflow:hidden;color:var(--muted);font-size:12px}.payPreview img{width:100%;max-height:160px;object-fit:contain;background:#fff}.payImageModal{position:fixed;inset:0;z-index:2600;display:grid;place-items:center;padding:18px}.payImageModal.hidden{display:none}.payImageBackdrop{position:absolute;inset:0;background:rgba(0,0,0,.68);backdrop-filter:blur(8px)}.payImageCard{position:relative;width:min(520px,94vw);max-height:92dvh;background:rgba(8,13,23,.98);border:1px solid rgba(255,255,255,.16);border-radius:18px;box-shadow:0 26px 90px rgba(0,0,0,.58);overflow:hidden}.payImageTop{display:flex;justify-content:space-between;align-items:center;padding:14px;border-bottom:1px solid rgba(255,255,255,.12)}.payImageBody{padding:16px;text-align:center;overflow:auto}.payScan{display:block;width:100%;max-height:72dvh;object-fit:contain;background:#fff;border-radius:14px;padding:10px}.payScanTag{margin-top:10px;color:var(--muted);font-weight:850}.payMissing{padding:28px;border:1px dashed rgba(255,255,255,.18);border-radius:14px;color:var(--muted)}`;document.head.appendChild(s);}
